site_name: Praxis LIVE documentation
pages:
  - 'Getting started':
    - 'Installation': 'installation.md'
    - 'Example projects': 'examples.md'
    - 'Architecture & terminology': 'architecture.md'
    - 'Main interface': 'main-interface.md'
    - 'Projects': 'projects.md'
    - 'Editors': 'editors.md'
    - 'Component editors': 'component-editors.md'
    - 'Custom components': 'custom-components.md'
  - 'Creating custom components':
    - 'Coding in Praxis LIVE'
    - 'Annotations': 'annotations.md'
    - 'Additional annotations': 'annotations-additional.md'
  - 'Advanced usage':
    - 'Distributed hubs'
    - 'CLI player'
    - 'Terminal'

theme: readthedocs

site_author: ""

repo_url: https://github.com/praxis-live/support

include_search: true

extra_css:
    - custom.css

#use_directory_urls: false

